name: Create Sample Jobs
on:
  push:
    branches:
      - main
jobs:
  firstjob:
     name : This is first job
     run-on : ubuntu-latest
     steps:
         -name : First Step
          uses : actions/checkout@v2
         -name : Second Step
          run  : env | sort
    
  
     
     
      
