name: Create Sample Jobs
on:
  push:
    branches:
      - main

jobs:
  firstjob:
     run-on : ubuntu-latest
     steps:
         run :  date 
     
  secondjob:
     run-on: windows-latest
     steps:
       run  : date
     
  ThirdJob:
     
     run-on: macos-latest
     steps:
       run : date -j -f %Y%m%d-%H%M%S 20180101-234852  +%Y/%m/%d\ %H:%M:%S
    
  
     
     
      
