name: my firstgithub jobs

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        run: ls
      - name: Run a one-line script
        run: echo Hello from Octo Organization
